services:
  - type: web
    name: tracient-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install .
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: TRACIENT_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false